### ISSUE TITLE
{listenbrainz-cache-path}/listenbrainz - No such file or directory

### ISSUE THREAD

**Issue by ghost** [StratusFearMe21/listenbrainz-mpv#3]
Problems running MPV without the 'listenbrainz' folder in the cache folder

```
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/lib.rs:144:46
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
fatal runtime error: failed to initiate panic, error 5
```

On [lib.rs#L144](https://github.com/StratusFearMe21/listenbrainz-mpv/blob/master/src/lib.rs#L144) the 'cache_path' is read without check that it exists (which it does on [lib.rs#L147](https://github.com/StratusFearMe21/listenbrainz-mpv/blob/c7c8d486eafe1c66fa4e40311e17757577100cd4/src/lib.rs#L147)).

if the folder is created manually there is no problem :grinning:

**Comment by StratusFearMe21** [comment]
Whoops, how'd that happen??? Thanks for telling me about this

**Comment by StratusFearMe21** [comment]
Latest commit should do the trick

**Comment by StratusFearMe21** [comment]
Whoops didn't mean to close that

**Comment by StratusFearMe21** [comment]
Anyway, *now* this should do the trick
